### ISSUE TITLE
Where do I state the sqlite file af data source?

### ISSUE THREAD

**Issue by sorentorp** [plieningerweb/sqlite_influx_sync#1]
Hi

Where do I state the sqlite file af data source? Or does it only pick up from memory?

**Comment by plieningerweb** [comment]
check https://github.com/plieningerweb/sqlite_influx_sync/blob/master/config.yaml#L3

and see http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlite

**Comment by sorentorp** [comment]
Thank you
